name: Klee

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    id-token: write

jobs:
    klee:
        if: always()
        uses: saasathon-2/integrations/.github/workflows/klee.yml@main
        with:
            api-url: https://klee.work
            pull-request: ${{ github.event.pull_request.number }}
